### ISSUE TITLE
some unitest failed

### ISSUE THREAD

**Issue by xue-yun-liang** [FlagOpen/FlagGems#94] opened 2024-07-03 08:34 UTC
When I run all the unit tests and there are a lot of them failed, I want to know if this is a bug that hasn't been fixed yet？Frequently occurring errors like the following.
![er](https://github.com/FlagOpen/FlagGems/assets/51466825/b2d63489-6ba8-468c-a8c3-0d4f09c59260)
![er2](https://github.com/FlagOpen/FlagGems/assets/51466825/586f3ac0-7307-4771-b7f2-621a88958469)

**Comment by xue-yun-liang** [comment] 2024-07-03 08:38
env: 
triton 2.3.1
pytorch 2.3.1

steps to reproduce：
1. pip install .
2. pytest tests/

**Comment by tongxin** [comment] 2024-07-03 09:45
Could you validate your test with Triton 2.2 as we are still working on supporting Triton 2.3.

**Comment by iclementine** [comment] 2024-07-03 09:47
We use a custom decorator `LibEntry` to bypass the decorators of triton runtime (`Autotuner`, `Heuristics`, `JITFunction`) to directly go to the `CompiledKernel`. But triton 2.3 has change the interface of `CompiledKernel` in 2.3, so `LibEntry` currently works with Triton 2.2.

**Comment by StrongSpoon** [comment] 2024-07-03 09:50
fixed in pr #89  and it's already merged.

**Comment by iclementine** [comment] 2024-07-03 10:04
- https://github.com/FlagOpen/FlagGems/pull/92 fixes the first error. This is caused by a mistake in the annotation for codegeneration.
- https://github.com/FlagOpen/FlagGems/pull/89 fixed the imcompatability with Triton 2.3. 

You can pull the latest codebase and test it again. Thanks

**Comment by xue-yun-liang** [comment] 2024-07-03 11:52
@iclementine thanks!

**Closed** 2024-07-05 01:46 UTC
