### ISSUE TITLE
使用FlagGems报错 AttributeError: module has no attribute '_wrapper' 和OSError: could not get source code

### ISSUE THREAD

**Issue by shushanxingzhe** [FlagOpen/FlagGems#55] opened 2024-06-05 11:12 UTC
当我使用开启FlagGems来训练模型来对比能带来多大加速效果时，报了如下两个错，请问怎么解决：

File "/usr/local/lib/python3.10/dist-packages/swift/llm/utils/argument.py", line 234, in __post_init__
  self.output_dir = add_version_to_work_dir(self.output_dir)
File "/usr/local/lib/python3.10/dist-packages/swift/utils/utils.py", line 59, in add_version_to_work_dir
  sub_folder = broadcast_string(sub_folder)
File "/usr/local/lib/python3.10/dist-packages/swift/utils/torch_utils.py", line 176, in broadcast_string
  first_zero = (tensor == 0).nonzero()[0].item()
File "/usr/local/lib/python3.10/dist-packages/flag_gems/ops/eq.py", line 28, in eq_scalar
  O = eq_func_scalar(A, B)
File "/usr/local/lib/python3.10/dist-packages/flag_gems/utils/pointwise_dynamic.py", line 625, in __call__
  overload = getattr(m, "_wrapper")
AttributeError: module '_gen_module_fa4c6a4330508d6b25e4d8648dd7f4f58dcfec5f20' has no attribute '_wrapper'

File "/root/.flaggems/pointwise_dynamic_fa4c6a4330508d6b25e4d8648dd7f4f58dcfec5f20_rank_1.py", line 40, in <module>
  def _jit_function(
File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 561, in decorator
  return JITFunction(
File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 440, in __init__
  self.starting_line_number = inspect.getsourcelines(fn)[1]
File "/usr/lib/python3.10/inspect.py", line 1121, in getsourcelines
  lines, lnum = findsource(object)
File "/usr/lib/python3.10/inspect.py", line 958, in findsource
  raise OSError('could not get source code')
OSError: could not get source code

**Comment by shushanxingzhe** [comment] 2024-06-05 11:14
我仅仅是在我原有训练模型的代码头部加了
import flag_gems
flag_gems.enable()

**Comment by Bowen12992** [comment] 2024-06-06 01:37
could you please supply some more example code and environment details for us？

**Comment by iclementine** [comment] 2024-06-06 01:46
It's probably a problem with the code generation of pointwise operators. I am working on supporting code genration in a multiprocessing environment.

**Comment by shushanxingzhe** [comment] 2024-06-06 01:57
@Bowen12992 It is hard to provide simple example code, since I used it in my multi-node multi-gpu training environment. It rely on a little complicate code. By the way, I used deepspeed and https://github.com/modelscope/swift in my case.

**Comment by iclementine** [comment] 2024-06-06 06:08
We have a fix for this.
https://github.com/FlagOpen/FlagGems/pull/56

**Comment by shushanxingzhe** [comment] 2024-06-06 06:42
Thanks, but I got another error in another model training


`../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [93,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [94,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [95,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/data/vjuicefs_speech_asr/public_data/72174954/whisper/run_speech_recognition_seq2seq_streaming_njob_k2.py", line 815, in <module>
    main()
  File "/data/vjuicefs_speech_asr/public_data/72174954/whisper/run_speech_recognition_seq2seq_streaming_njob_k2.py", line 770, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2216, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3238, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3264, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1842, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/modeling_whisper.py", line 1772, in forward
    loss = loss_fct(lm_logits.view(-1, self.config.vocab_size), labels.reshape(-1))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
  File "/usr/local/lib/python3.10/dist-packages/flag_gems/ops/cross_entropy_loss.py", line 292, in cross_entropy_loss
    return CrossEntropyLoss.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/flag_gems/ops/cross_entropy_loss.py", line 223, in forward
    log_softmax_and_mul_kernel[grid](
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 167, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flag_gems/utils/libentry.py", line 36, in run
    kernel = self.fn.run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/autotuner.py", line 143, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/autotuner.py", line 143, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/autotuner.py", line 122, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/usr/local/lib/python3.10/dist-packages/triton/testing.py", line 102, in do_bench
    fn()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/autotuner.py", line 110, in kernel_call
    self.fn.run(
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/autotuner.py", line 305, in run
    return self.fn.run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 425, in run
    kernel.run(grid_0, grid_1, grid_2, kernel.num_warps, kernel.num_ctas,  # number of warps/ctas per instance
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 255, in __getattribute__
    self._init_handles()
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 250, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills = driver.utils.load_binary(
RuntimeError: Triton Error [CUDA]: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7ff7d6d9e4d7 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7ff7d6d6836b in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7ff7e7da3fa8 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x137bb (0x7ff7e7d747bb in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x22d80 (0x7ff7e7d83d80 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4ccec6 (0x7ff7b65b9ec6 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3ee77 (0x7ff7d6d83e77 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x1be (0x7ff7d6d7c69e in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x9 (0x7ff7d6d7c7b9 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x752478 (0x7ff7b683f478 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #10: THPVariable_subclass_dealloc(_object*) + 0x305 (0x7ff7b683f805 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x13bf7f (0x557817ad5f7f in /usr/bin/python)
frame #12: <unknown function> + 0x13bd1c (0x557817ad5d1c in /usr/bin/python)
frame #13: <unknown function> + 0x12d8ef (0x557817ac78ef in /usr/bin/python)
frame #14: _PyModule_ClearDict + 0x296 (0x557817b840e6 in /usr/bin/python)
frame #15: <unknown function> + 0x26807a (0x557817c0207a in /usr/bin/python)
frame #16: Py_FinalizeEx + 0x148 (0x557817bfeb98 in /usr/bin/python)
frame #17: Py_RunMain + 0x173 (0x557817bf02d3 in /usr/bin/python)
frame #18: Py_BytesMain + 0x2d (0x557817bc6cad in /usr/bin/python)
frame #19: <unknown function> + 0x29d90 (0x7ff7ee31ad90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #20: __libc_start_main + 0x80 (0x7ff7ee31ae40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #21: _start + 0x25 (0x557817bc6ba5 in /usr/bin/python)`

**Comment by StrongSpoon** [comment] 2024-06-06 08:33
Cross_entropy_loss accepts a list of tensor index as argument 'target'. This error might be caused by invalid index value. I suggest checking if any element in target tensor is out of range.

**Comment by StrongSpoon** [comment] 2024-06-17 01:35
we figure out that cross_entropy_loss should deal with target value == -100. argument ignore_index is not supported temporarily, and this will be fixed soon.

**Closed as completed** 2024-06-21 08:11 UTC
